{
 "title": "kVDI Runtime Metrics",
 "description": "kVDI runtime metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active App Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kvdi_http_requests_total{path=\"/api/readyz\", code=\"200\"})"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kvdi_active_display_streams)",
     "legendFormat": "Display Streams"
    },
    { "expr": "sum(kvdi_active_audio_streams)", "legendFormat": "Audio Streams" }
   ]
  },
  {
   "title": "Requests per second by path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kvdi_http_requests_total[5m])) by (path,method)",
     "legendFormat": "{{method}} {{ path }}"
    }
   ]
  },
  {
   "title": "Requests per second by status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kvdi_http_requests_total[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "90% quantile request latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(kvdi_http_request_duration_seconds_bucket[10m]))) * 1000\n"
    }
   ]
  },
  {
   "title": "Requests per second (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kvdi_http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Bytes per second sent over display streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kvdi_ws_display_bytes_sent_total[5m])) by (desktop)",
     "legendFormat": "{{ desktop }}"
    }
   ]
  },
  {
   "title": "Bytes per second received over display streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kvdi_ws_display_bytes_rcvd_total[5m])) by (desktop)",
     "legendFormat": "{{ desktop }}"
    }
   ]
  },
  {
   "title": "Bytes per second sent over audio streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kvdi_ws_audio_bytes_sent_total[5m])) by (desktop)",
     "legendFormat": "{{ desktop }}"
    }
   ]
  },
  {
   "title": "Bytes per second received over audio streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kvdi_ws_audio_bytes_rcvd_total[5m])) by (desktop)",
     "legendFormat": "{{ desktop }}"
    }
   ]
  }
 ]
}